services:
  - type: web
    name: superhero-power-predictor
    runtime: docker
    dockerfilePath: ./deployments/Dockerfile
    dockerContext: .
    env: docker
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
